apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: static-efs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeClaim: Retain
  volumeMode: Filesystem
  storageClassName: "" # should be empty in static
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-036d23e179ae44563
 
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: efs-claim
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: "" 
  resources:
    capacity:
      requests:
        storage: 10Gi

---

apiVersion: v1 
kind: Pod
metadata: 
  name: demo
  labels:
    purpose: efs-demo
spec: 
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: vol-efs
          mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  volumes:
  - name: vol-efs
    persistentVolumeClaim:
      claimName: efs-claim
  
  
