apiVersion: v1 
kind: Deployment
metadata:
  name: node-affinity
spec:
  selector:
    matchLabels:
      app: affinity 
  template:
    metadata: 
      labels: 
        app: affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelector:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
              - us-east-1b