apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affinity
  template:
    metadata:
      labels:
        app: affinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoreDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1b
      containers:
        - name: nginx
          image: nginx
